# Generated by Django 4.2.8 on 2024-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_teacher_user_is_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=True),
        ),
    ]
