# Generated by Django 4.2.7 on 2023-12-05 21:29

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
