# Generated by Django 4.2.8 on 2023-12-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_student_time_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
