# Generated by Django 4.2.8 on 2023-12-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_lesson_options_student_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
