# Generated by Django 4.2.8 on 2024-01-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_lesson_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
