# Generated by Django 4.2.8 on 2024-01-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_student_additional_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='paid',
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.JSONField(blank=True, default=[''], null=True),
        ),
    ]
