# Generated by Django 4.2.8 on 2024-06-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_remove_lesson_paid_alter_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('bill', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lesson', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='scheduler.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.student')),
            ],
        ),
    ]
