# Generated by Django 4.2.8 on 2024-06-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_lesson_payment_date_student_balance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
